# Site Information
title: Phrasing Insurrection: A Computational Study of the Grammars of Collective Enslaved Resistance in the South Carolina Gazette and Virginia Gazette between 1732 and 1775
description: A master's thesis completed in the University of Colorado Boulder's history department by Chloe Zehr.
theme: jekyll-theme-minimal
