# Site Information
title: "Phrasing Insurrection: A Computational Study of the Grammars of Collective Enslaved Resistance"
description: "A master's thesis completed in the University of Colorado Boulder's history department by Chloe Zehr."
theme: minimal
