# Site Information
title: "Phrasing Insurrection: A Computational Study of the Grammars of Collective Enslaved Resistance in the South Carolina Gazette and Virginia Gazette in the Eighteenth Century"
description: "A master's thesis completed in the University of Colorado Boulder's history department by Chloe Zehr."
baseurl: "/phrasing-insurrection"  # Matches your repository name
url: "https://chloeazehr.github.io"  # Your GitHub Pages URL

# Theme
remote_theme: mmistakes/minimal-mistakes  # Uses Minimal Mistakes from GitHub
plugins:
  - jekyll-seo-tag    # SEO plugin
  - jekyll-sitemap    # Generates sitemap.xml
  - jekyll-feed       # Generates RSS feed for blog posts

# Defaults for all Pages
defaults:
  - scope:
      path: ""  # Applies to all files
    values:
      layout: single
      toc: true         # Enables the table of contents
      toc_sticky: true  # Makes the TOC sticky as you scroll
      sidebar: true     # Enables the sidebar on all pages

# Minimal Mistakes Configuration
minimal_mistakes_skin: "default"  # Adjust for different Minimal Mistakes styles
header:
  title: "Phrasing Insurrection"
  description: "A master's thesis on enslaved resistance in the South Carolina and Virginia Gazette."

# Sidebar Configuration
sidebar:
  - title: "Navigation"
    nav:
      - title: "Home"
        url: /
      - title: "About"
        url: /about/
      - title: "Project Description"
        url: /project-description/
      - title: "Why Digital History?"
        url: /why-digital-history/
      - title: "Methodology and Data"
        url: /methodology-and-data/
      - title: "Tools and Resources"
        url: /tools-and-resources/

# Navigation Links for Header (Optional)
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Project Description"
    url: /project-description/
  - title: "Why Digital History?"
    url: /why-digital-history/
  - title: "Methodology and Data"
    url: /methodology-and-data/
  - title: "Tools and Resources"
    url: /tools-and-resources/

# Footer Links (Optional)
footer_links:
  - title: "GitHub"
    url: "https://github.com/chloeazehr/phrasing-insurrection"
  - title: "Contact"
    url: "chloeazehr@gmail.com"

# Markdown Renderer
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown for compatibility

# Permalinks
permalink: pretty  # Clean URLs (no .html extension)

