title: "Phrasing Insurrection"
remote_theme: "just-the-docs/just-the-docs" # Use remote_theme for GitHub Pages
just_the_docs:
  nav_order: 1
  show_toc: true
  search_enabled: true

# Include additional folders/files
include:
  - assets

# Navigation menu
nav:
  - title: "Home"
    url: "/"
    nav_order: 1
  - title: "About"
    url: "/about/"
    nav_order: 2
  - title: "Project Description"
    url: "/project-description/"
    nav_order: 3
  - title: "Methodology and Data"
    url: "/methodology-and-data/"
    nav_order: 4
  - title: "Why Digital History?"
    url: "/why-digital-history/"
    nav_order: 5
  - title: "Tools and Resources"
    url: "/tools-and-resources/"
    nav_order: 6
